### ISSUE TITLE
🐛[ Bug ] : JavaScript Cookie and Local Storage Implementation

### ISSUE THREAD

**Issue by iammuhammedfuhad** [iammuhammedfuhad/PhishGuard#21]
### Discussed in https://github.com/iammuhammedfuhad/PhishGuard/discussions/20

<div type='discussions-op-text'>

<sup>Originally posted by **iammuhammedfuhad** May 22, 2023</sup>
## Description:
We have recently added JavaScript code to our application in order to create a cookie and use local storage to save the user's current level. Unfortunately, we have encountered a problem with this implementation, and we are actively working to resolve it. We are seeking assistance from the community to help us identify and fix the issue.

**Current Behavior:**
- JavaScript code added to create a cookie and utilize local storage.
- User's current level is intended to be saved using these mechanisms.
- However, we have discovered a bug in this implementation.

**Expected Behavior:**
- The cookie should be created successfully.
- Local storage should accurately store and retrieve the user's current level.

**Steps to Reproduce:**
1. Load the application.
2. Perform actions that trigger level changes.
3. Check if the cookie is being created and the level is being stored in local storage.
4. Observe any unexpected behavior or errors encountered.

**Additional Context:**
- We have examined the code and believe the issue lies within our JavaScript implementation.
- We have reviewed relevant documentation and attempted to troubleshoot the problem internally.
- However, we have been unable to pinpoint the root cause and resolve the issue.
- Any assistance or guidance from the community would be greatly appreciated.

**Expected Contribution:**
- Help with identifying the bug in our JavaScript code.
- Suggestions or solutions to fix the issue related to cookie creation and local storage usage.
- Feedback on potential improvements to the current implementation.

📝 Note: We are actively working on resolving this issue, but external assistance would be invaluable in expediting the process. Thank you in advance for your contributions!
</div>

**Comment by Rahulditi** [comment]
can you assign it to me?

**Comment by iammuhammedfuhad** [comment]
@Rahulditi Yaa sure, you can work on it👍🏻.
Anyway a big thanks for contributing to our project 😊.

**Comment by Rahulditi** [comment]
Thank you, I'm currently working on it. Is there a way to contact you?

**Comment by iammuhammedfuhad** [comment]
You can contact me here, else you can contact me on Instagram id :- iam.muhammedfuhad.
The better way for contacting and discussion is github. Anyway your choice 🙃

**Comment by Rahulditi** [comment]
Thank you, is it a mandatory to use both cookies and local Storage?

**Comment by Rahulditi** [comment]
or can i use only local Storage Alone?

**Comment by iammuhammedfuhad** [comment]
Yaa you can👍🏻

**Comment by iammuhammedfuhad** [comment]
Its not mandatory to use both.

**Comment by iammuhammedfuhad** [comment]
Can you come on a specific time, so I can connect with you to talk about the problems and our project.

**Comment by Rahulditi** [comment]
I opened a pull request on this issue kindly check it.

**Comment by iammuhammedfuhad** [comment]
I checked it. First of all I appreciate you for solving this bug 👏.
This issue will be closed when we complete solving the award page. If you wish to work with it you can 😊.

**Comment by Rahulditi** [comment]
Thank you, I will be looking into the award page issue too....👍

**Comment by iammuhammedfuhad** [comment]
Hhm😊

**Comment by iammuhammedfuhad** [comment]
![Rahul](https://github.com/iammuhammedfuhad/PhishGuard/assets/115918224/aa8219b9-9624-4643-b12b-deb5344dc72f)

This is small appreciation certificate for contribution. Share it ✨️

**Comment by iammuhammedfuhad** [comment]
@Rahulditi I worked on the bug and now it's fixed. Thankyou for your contribution.
