### ISSUE TITLE
YouTube Chat

### ISSUE THREAD

**Issue by AliMora83** [iammuhammedfuhad/PhishGuard#8]
Hey there.

I saw you mention this in EddieHub YouTube Video, just now🥳

Was it you?🤔

**Comment by iammuhammedfuhad** [comment]
Yaa its me😍

**Comment by iammuhammedfuhad** [comment]
contribute on this project 🙌

**Comment by AliMora83** [comment]
I can help with Front-end 🥳

**Comment by iammuhammedfuhad** [comment]
Ok do it👍🏻, New tasks will be announced soon💥

**Comment by iammuhammedfuhad** [comment]
Please give a ⭐️ star to our repo.

**Comment by AliMora83** [comment]
Well done 🥳

**Comment by iammuhammedfuhad** [comment]
Hi @AliMora83 

Can you contribute to our project by styling the css of badges,html page..?
